"use client";

import { useEffect, useMemo, useState } from "react";
import { PillarAActivityChart } from "@/components/pillar-a-activity-chart";
import { PillarAReference } from "@/components/pillar-a-reference";
import { PillarAAtc4 } from "@/components/pillar-a-atc4";
import { PillarAFlowVisuals } from "@/components/pillar-a-flow-visuals";
import { PillarAOsmed } from "@/components/pillar-a-osmed";
import { ResponsiveContainer, LineChart, Line, BarChart, Bar, CartesianGrid, XAxis, YAxis, Tooltip, Cell } from "recharts";

type Annual = {year:number;region:string;group:string;channel:string;spend:number|null;packs:number|null;spendYoy:number|null;population:number|null;perResident:number|null;missingSpendCells:number;missingPackCells:number;months:number};
type Data = {version:string;regions:Record<string,string>;annual:Annual[];monthly:{year:number;month:number;region:string;group:string;channel:string;spend:number|null;packs:number|null}[];activity:{year:number;region:string;ordinary_days:number;day_accesses:number}[];candidates:{atc5:string;group:string;ingredient_or_reference_names:string;aware:string;aware_status:string;public_parent_years:string}[]};
const groups:Record<string,string>={antibiotics:"Antibiotici · J01",antifungals:"Antifungini sistemici · J02A"};
const channels:Record<string,string>={direct:"Acquisti diretti",convenzionata:"Convenzionata"};
// The SDO editions abbreviate the same region differently; preserve source rows.
const activityName=(name:string)=>name==='Friuli V.G.'?'Friuli Venezia Giulia':name;
// AIFA reports the two autonomous provinces as separate units, which is why they
// sit beside the regions. Their parent region is named so the relationship is
// explicit. A combined Trentino-Alto Adige rate would have to sum the numerators
// and the denominators; averaging the two provinces' rates would be wrong.
const PROVINCES:Record<string,string>={"041":"Prov. aut. di Bolzano","042":"Prov. aut. di Trento"};
const territoryLabel=(code:string,name:string)=>PROVINCES[code]?`${PROVINCES[code]} · Trentino-Alto Adige`:name;
const RANK_MEASURES:Record<string,string>={spend:"Spesa riportata (€)",packs:"Confezioni riportate",perResident:"Spesa per residente (€)"};
const RANK_ORDER:Record<string,string>={desc:"Dal più alto al più basso",asc:"Dal più basso al più alto"};
const fmt=(v:number|null|undefined,d=0)=>v==null?"N/D":new Intl.NumberFormat("it-IT",{maximumFractionDigits:d}).format(v);
const compact=(v:number)=>new Intl.NumberFormat("it-IT",{notation:"compact",maximumFractionDigits:1}).format(v);
const pct=(v:number|null|undefined)=>v==null?"N/D":`${v>=0?"+":""}${fmt(v*100,1)}%`;
// Theme tokens, not fixed light values: the tooltip was white-on-navy text
// floating over a dark page in dark mode.
const tipStyle={borderRadius:12,border:"1px solid hsl(var(--border))",background:"hsl(var(--card))",color:"hsl(var(--card-foreground))",boxShadow:"0 12px 30px rgba(0,0,0,.18)"};

function Panel({title,note,control,children}:{title:string;note:string;control?:React.ReactNode;children:React.ReactNode}){return <section className="min-w-0 rounded-2xl border bg-card p-5 shadow-sm sm:p-6"><div className="mb-6 flex flex-wrap items-start justify-between gap-x-8 gap-y-4"><div className="min-w-0 grow basis-72"><h2 className="font-display text-xl font-semibold">{title}</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{note}</p></div>{control&&<div className="w-full sm:w-60 sm:shrink-0">{control}</div>}</div>{children}</section>;}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:Record<string,string>}){return <label className="flex min-w-0 flex-col gap-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">{label}<select className="h-11 rounded-lg border bg-background px-3 text-sm font-medium normal-case tracking-normal text-foreground" value={value} onChange={e=>onChange(e.target.value)}>{Object.entries(options).sort(([a],[b])=>/^\d+$/.test(a)&&/^\d+$/.test(b)?Number(a)-Number(b):0).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>;}

export function PillarAPublic(){
  const [data,setData]=useState<Data|null>(null),[error,setError]=useState(false);
  const [loadedKey,setLoadedKey]=useState('');
  const [region,setRegion]=useState("000"),[group,setGroup]=useState("antibiotics"),[channel,setChannel]=useState("direct"),[metric,setMetric]=useState("spend"),[activityRegion,setActivityRegion]=useState("ITALIA"),[query,setQuery]=useState("");
  // The territorial comparison owns its own ranking controls. Previously it was
  // sorted by a selector living in a different card, so there was no way to see
  // what the ranking was based on or to change it from the table.
  const [rankMetric,setRankMetric]=useState("spend"),[rankOrder,setRankOrder]=useState("desc");
  const requestKey=`${region}/${group}/${channel}`;
  useEffect(()=>{const controller=new AbortController();setError(false);fetch(`/api/pillar-a/series?${new URLSearchParams({region,group,channel})}`,{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(result=>{if(!controller.signal.aborted){setData(result);setLoadedKey(requestKey);}}).catch(e=>{if(e.name!=="AbortError")setError(true);});return()=>controller.abort();},[region,group,channel,requestKey]);
  const annual=useMemo(()=>data?.annual.filter(r=>r.region===region&&r.group===group&&r.channel===channel)??[],[data,region,group,channel]);
  if(error)return <div className="mx-auto max-w-7xl p-10" role="alert">Dati temporaneamente non disponibili. Ricarica la pagina.</div>;
  if(!data||loadedKey!==requestKey)return <div className="mx-auto max-w-7xl p-10" role="status">Caricamento delle serie verificate…</div>;
  const latest=annual.at(-1), metricKey=metric as "spend"|"packs"|"perResident";
  const metricLabel=metric==="spend"?"Spesa riportata (€)":metric==="packs"?"Confezioni riportate":"Spesa per residente (€)";
  // Ranked on its own measure and direction, chosen in the panel itself. A
  // territory missing the measure is dropped rather than ranked as zero.
  const rankKey=rankMetric as "spend"|"packs"|"perResident";
  const ranked=data.annual.filter(r=>r.year===2025&&r.region!=="000"&&r.group===group&&r.channel===channel&&r[rankKey]!==null)
    // Territory name breaks ties so the order is stable between renders rather
    // than depending on the order rows arrived in.
    .sort((a,b)=>(rankOrder==="asc"?(a[rankKey]??0)-(b[rankKey]??0):(b[rankKey]??0)-(a[rankKey]??0))
      ||territoryLabel(a.region,data.regions[a.region]).localeCompare(territoryLabel(b.region,data.regions[b.region])));
  // Standard competition ranking: equal values share a position and the next
  // position skips accordingly (1, 2, 2, 4). Successive numbers would have
  // implied an ordering between territories the measure does not establish.
  const positions=ranked.map((r,i,all)=>i>0&&all[i-1][rankKey]===r[rankKey]?null:i+1);
  positions.forEach((v,i)=>{if(v===null)positions[i]=positions[i-1];});
  const tied=new Set(ranked.filter((r,i,all)=>all.some((o,j)=>j!==i&&o[rankKey]===r[rankKey])).map(r=>r.region));
  const rankOf=(()=>{const i=ranked.findIndex(r=>r.region===region);return i<0?0:positions[i] as number;})();
  const seasons=Array.from({length:12},(_,i)=>({month:["Gen","Feb","Mar","Apr","Mag","Giu","Lug","Ago","Set","Ott","Nov","Dic"][i],...Object.fromEntries([2023,2024,2025].map(y=>[String(y),data.monthly.find(r=>r.year===y&&r.month===i+1&&r.region==='000'&&r.group===group&&r.channel===channel)?.spend??null]))}));
  const monthlyComparison=Array.from({length:12},(_,i)=>{
    const share=(code:string)=>{const total=data.annual.find(r=>r.year===2025&&r.region===code&&r.group===group&&r.channel===channel)?.spend;const month=data.monthly.find(r=>r.year===2025&&r.month===i+1&&r.region===code&&r.group===group&&r.channel===channel)?.spend;return total!=null&&total>0&&month!=null?100*month/total:null;};
    return {month:seasons[i].month,italia:share('000'),territorio:share(region)};
  });
  const activity=data.activity.filter(r=>activityName(r.region)===activityRegion);
  const candidates=data.candidates.filter(r=>r.group===group&&`${r.atc5} ${r.ingredient_or_reference_names}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="mx-auto max-w-7xl space-y-8 px-5 py-10 sm:py-14">
    <div className="grid gap-6 md:grid-cols-[1fr_auto]"><div><p className="mb-3 text-xs font-semibold uppercase tracking-[.2em] text-primary">Pillar A / Osservatorio pubblico</p><h1 className="font-display max-w-3xl text-3xl font-semibold leading-tight sm:text-5xl">Dieci anni di dati.<br/><span className="text-primary">Una lettura più precisa.</span></h1><p className="mt-5 max-w-2xl text-base leading-relaxed text-muted-foreground">Spesa e confezioni per territorio, contesto demografico e attività ospedaliera. Fonti pubbliche, perimetri distinti, risultati riproducibili.</p></div><div className="self-end rounded-xl border bg-card p-4 text-sm"><p className="font-semibold">AIFA · ISTAT · Ministero della Salute</p><p className="mt-2 text-muted-foreground">Aggiornamento VIS · 23 settembre 2026</p></div></div>
    <div className="grid gap-4 rounded-2xl border bg-card p-5 sm:grid-cols-3"><Select label="Territorio" value={region} onChange={setRegion} options={Object.fromEntries(Object.entries(data.regions).map(([c,n])=>[c,territoryLabel(c,n)]))}/><Select label="Famiglia" value={group} onChange={setGroup} options={groups}/><Select label="Flusso AIFA" value={channel} onChange={setChannel} options={channels}/></div>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[
      ["Spesa riportata · 2025",latest?.spend==null?"N/D":`€ ${compact(latest.spend)}`,channels[channel]],
      ["Variazione spesa · 2025 / 2024",pct(latest?.spendYoy),"Stesso territorio, famiglia e flusso"],
      ["Confezioni · 2025",latest?.packs==null?"N/D":compact(latest.packs),"Unità di confezionamento"],
      ["Euro per residente · 2025",latest?.perResident==null?"N/D":`€ ${fmt(latest.perResident,2)}`,"Popolazione al 1° gennaio"],
    ].map(([label,value,note],i)=><div key={label} className={`rounded-2xl border p-5 ${i===0?'bg-[#173b49] text-white':'bg-card'}`}><p className={`text-xs ${i===0?'text-teal-100':'text-muted-foreground'}`}>{label}</p><p className="my-4 font-display text-3xl font-semibold tabular-nums">{value}</p><p className={`text-xs ${i===0?'text-teal-100':'text-muted-foreground'}`}>{note}</p></div>)}</div>
    <p className="rounded-lg border-l-4 border-primary bg-secondary/50 px-4 py-3 text-sm leading-relaxed">{group==="antifungals"?"Gli antifungini hanno una serie dedicata. La classificazione AWaRe non si applica.":"AWaRe è una classificazione degli antibiotici. Le confezioni di questa serie non sono convertite in DDD."} Il perimetro ATC è costante; le classificazioni correnti costituiscono una lettura retrospettiva.</p>
    {region!=="000"&&<Panel title="Profilo mensile · territorio e Italia · 2025" note={`${data.regions[region]} e Italia: percentuale della spesa annuale registrata in ciascun mese, nello stesso flusso. La scala comune confronta la distribuzione temporale, non i volumi o l’incidenza delle infezioni.`}><div className="mb-3 flex gap-6 text-sm"><span className="text-primary">● {data.regions[region]}</span><span>● Italia</span></div><div className="h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={monthlyComparison}><CartesianGrid strokeDasharray="3 5" vertical={false}/><XAxis dataKey="month"/><YAxis tickFormatter={v=>`${v}%`}/><Tooltip contentStyle={tipStyle} formatter={v=>`${fmt(Number(v),1)}%`}/><Line name="Italia" dataKey="italia" stroke="#65788b" dot={false}/><Line name={data.regions[region]} dataKey="territorio" stroke="#13998f" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></div></Panel>}
    <div className="grid gap-6 lg:grid-cols-[1.4fr_1fr]">
      <Panel title="La traiettoria nel tempo" note={`${data.regions[region]} · ${groups[group]} · ${channels[channel]} · ${metricLabel}. Nessuna interpolazione dei valori mancanti.`} control={<Select label="Misura nei grafici" value={metric} onChange={setMetric} options={{spend:"Spesa (€)",packs:"Confezioni",perResident:"Euro per residente"}}/>}><div className="h-80" role="img" aria-label={`Serie annuale ${metricLabel}`}><ResponsiveContainer width="100%" height="100%"><LineChart data={metric==='perResident'?annual.filter(r=>r.perResident!==null):annual} margin={{left:0,right:15,top:10,bottom:5}}><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="#dbe5e8"/><XAxis dataKey="year" tick={{fontSize:11}} axisLine={false} tickLine={false}/><YAxis tickFormatter={compact} tick={{fontSize:11}} width={65} axisLine={false} tickLine={false}/><Tooltip contentStyle={tipStyle} formatter={v=>[fmt(Number(v),2),metricLabel]}/><Line type="linear" dataKey={metricKey} stroke="#13998f" strokeWidth={3} dot={{r:3}} connectNulls={false}/></LineChart></ResponsiveContainer></div></Panel>
      <Panel title="Quanto cambia ogni anno" note="Variazione della spesa rispetto all’anno precedente. Il colore indica la direzione, non un giudizio di performance."><div className="h-80" role="img" aria-label="Variazioni annuali della spesa"><ResponsiveContainer width="100%" height="100%"><BarChart data={annual.map(r=>({...r,change:r.spendYoy==null?null:r.spendYoy*100}))}><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="#dbe5e8"/><XAxis dataKey="year" tick={{fontSize:10}} axisLine={false}/><YAxis tickFormatter={v=>`${v}%`} tick={{fontSize:10}}/><Tooltip contentStyle={tipStyle} formatter={v=>[`${fmt(Number(v),1)}%`,"Variazione"]}/><Bar dataKey="change" radius={[4,4,0,0]}>{annual.map(r=><Cell key={r.year} fill={(r.spendYoy??0)>=0?'#169b91':'#65788b'}/>)}</Bar></BarChart></ResponsiveContainer></div></Panel>
    </div>
    <div className={region==="000"?"grid gap-6 lg:grid-cols-2":"grid gap-6"}>{region==="000"&&<Panel title="Profilo mensile nazionale" note={`Italia · ${groups[group]} · ${channels[channel]} · spesa in euro. Il profilo descrive le registrazioni del flusso, non l’incidenza delle infezioni.`}><div className="mb-3 flex gap-5 text-xs">{[2023,2024,2025].map((y,i)=><span key={y} style={{color:['#98aaa9','#52697d','#159b91'][i]}}>● {y}</span>)}</div><div className="h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={seasons}><CartesianGrid strokeDasharray="3 5" vertical={false}/><XAxis dataKey="month" tick={{fontSize:11}}/><YAxis width={65} tickFormatter={compact} tick={{fontSize:11}}/><Tooltip contentStyle={tipStyle} formatter={v=>`€ ${fmt(Number(v))}`}/>{[2023,2024,2025].map((y,i)=><Line key={y} dataKey={String(y)} stroke={['#98aaa9','#52697d','#159b91'][i]} strokeWidth={y===2025?3:1.5} dot={false}/>)}</LineChart></ResponsiveContainer></div></Panel>}
    <Panel title="Confronto territoriale · 2025" note={`Graduatoria dei territori per ${RANK_MEASURES[rankMetric].toLowerCase()} nel 2025, ${RANK_ORDER[rankOrder].toLowerCase()}. Ordina spesa e volumi, non la qualità clinica né l’appropriatezza: popolazione, composizione e flussi variano fra territori e il confronto non identifica risparmi conseguibili.`} control={<div className="space-y-3"><Select label="Ordina per" value={rankMetric} onChange={setRankMetric} options={RANK_MEASURES}/><Select label="Direzione" value={rankOrder} onChange={setRankOrder} options={RANK_ORDER}/></div>}>{region!=="000"&&rankOf>0&&<p className="mb-3 rounded-lg bg-secondary/50 px-4 py-2.5 text-sm"><span className="font-semibold">{territoryLabel(region,data.regions[region])}</span>: {rankOf}º su {ranked.length} per {RANK_MEASURES[rankMetric].toLowerCase()}.</p>}<div className="max-h-80 overflow-auto"><table className="w-full text-sm"><thead className="sticky top-0 bg-card text-left text-xs text-muted-foreground"><tr><th className="py-3 pr-2 text-right">#</th><th className="py-3">Territorio</th><th className="py-3 text-right">{RANK_MEASURES[rankMetric]}</th></tr></thead><tbody>{ranked.map((r,i)=><tr key={r.region} className={`border-t ${r.region===region?"bg-secondary/60 font-semibold":""}`}><td className="py-2.5 pr-2 text-right font-mono text-muted-foreground">{positions[i]}{tied.has(r.region)?"=":""}</td><td className="py-2.5">{territoryLabel(r.region,data.regions[r.region])}</td><td className="text-right font-mono">{fmt(r[rankKey],rankMetric==="perResident"?2:0)}</td></tr>)}</tbody></table></div><p className="mt-3 text-xs text-muted-foreground">Le posizioni seguono la graduatoria standard: a parità di valore i territori condividono la posizione, segnalata con “=”, e la successiva salta di conseguenza. Le Province autonome di Bolzano e Trento sono rilevate separatamente da AIFA e restano distinte: un dato unico per il Trentino-Alto Adige richiederebbe la somma dei numeratori e dei denominatori, non la media dei due tassi.{rankMetric==="perResident"?" La spesa per residente usa i rispettivi totali comunali ISTAT.":""}</p></Panel></div>
    <Panel title="Attività ospedaliera · 2021–2024" note="Contesto di attività: serve a distinguere un consumo di antibiotici che cresce perché crescono i ricoveri da uno che cresce a parità di attività. Fonte SDO, ricoveri per acuti: giornate ordinarie e accessi diurni restano distinti e non misurano da soli la performance."><div className="mb-6 max-w-sm"><Select label="Territorio SDO" value={activityRegion} onChange={setActivityRegion} options={Object.fromEntries([...new Set(data.activity.map(r=>activityName(r.region)))].map(r=>[r,r]))}/></div><p className="mb-6 rounded-lg border-l-4 border-primary bg-secondary/50 px-4 py-3 text-sm leading-relaxed">A cosa serve per la resistenza antimicrobica: da sola l’attività non misura né dimostra la resistenza. Serve come contesto del volume, perché senza di essa un aumento dei consumi non è distinguibile da un aumento dei ricoveri. Un indicatore come le DDD per 100 giornate richiede un denominatore di attività con perimetro, periodo e definizione coerenti con il numeratore: questa serie SDO non è stata verificata equivalente a quella che OSMED usa per il PNCAR, quindi qui resta un contesto descrittivo e non viene usata per normalizzare i consumi.</p><div className="grid gap-6 lg:grid-cols-2"><PillarAActivityChart data={activity} field="ordinary_days" title="Giornate di degenza ordinaria"/><PillarAActivityChart data={activity} field="day_accesses" title="Accessi in regime diurno"/></div></Panel>
    {group==='antibiotics'&&<Panel title="Consumo ospedaliero · verso l’obiettivo PNCAR" note="Posizionamento territoriale sullo stesso indicatore del piano: DDD per 100 giornate. Riferimento OSMED 2024, separato dalle serie di spesa e confezioni."><PillarAOsmed region={region} name={data.regions[region]}/></Panel>}
    <Panel title="Classificazione e principi attivi" note="Esplora le categorie ATC4 e i codici ATC5 nei riferimenti AIFA/WHO. I conteggi descrivono l’anagrafica, non il consumo delle singole molecole.">
      <p className="mb-4 rounded-lg bg-secondary/50 p-4 text-sm leading-relaxed">AWaRe descrive la stewardship antibiotica. ABC descrive invece la concentrazione della spesa: nessuna delle due è una graduatoria generale di efficacia. Access non significa uso libero. <a href="https://www.who.int/publications/i/item/B09489" className="text-primary underline">Definizione WHO</a></p>
      <input aria-label="Cerca codice o principio attivo" placeholder="Cerca codice ATC o principio attivo…" className="mb-4 w-full rounded-lg border bg-background px-4 py-3 text-sm" value={query} onChange={e=>setQuery(e.target.value)}/>
      <PillarAReference candidates={candidates}/>
    </Panel>
    <PillarAAtc4 region={region} regionName={data.regions[region]} group={group} channel={channel}/>
    <Panel title="Come leggere gli indicatori" note="Unità diverse rispondono a domande diverse."><dl className="grid gap-5 text-sm md:grid-cols-2">
      <div><dt className="font-semibold">Confezioni e DDD</dt><dd className="mt-2 text-muted-foreground">Le confezioni sono unità commerciali. La DDD è un’unità tecnica standard: per convertirle occorrono quantità e riferimento DDD del prodotto. Non è una dose prescritta al paziente.</dd></div>
      <div><dt className="font-semibold">DDD / 100 giornate</dt><dd className="mt-2 text-muted-foreground">DDD totali ÷ attività ospedaliera coerente × 100. Misura l’intensità di consumo rispetto all’attività. La definizione del denominatore deve restare uguale nel confronto.</dd></div>
      <div><dt className="font-semibold">DDD / 1.000 abitanti / giorno</dt><dd className="mt-2 text-muted-foreground">DDD totali ÷ popolazione ÷ giorni del periodo × 1.000. È un indicatore di consumo sulla popolazione, diverso dall’intensità ospedaliera.</dd></div>
      <div><dt className="font-semibold">Euro per residente</dt><dd className="mt-2 text-muted-foreground">Spesa del periodo ÷ residenti al 1° gennaio. Permette una lettura per dimensione del territorio, senza correggere per età o complessità dei casi.</dd></div>
    </dl></Panel>
    <Panel title="Dalla visualizzazione alla fonte" note="Ogni serie conserva periodo, flusso e fonte. Le celle vuote non diventano zero; le somme rappresentano i valori numerici riportati."><div className="grid gap-6 md:grid-cols-3"><div><h3 className="font-semibold">Spesa e confezioni</h3><p className="mt-2 text-sm text-muted-foreground">AIFA 2016–2025. Acquisti diretti e convenzionata sono separati; non equivalgono automaticamente ai canali locali DD e CO.</p></div><div><h3 className="font-semibold">Popolazione residente</h3><p className="mt-2 text-sm text-muted-foreground">ISTAT, 1° gennaio: ricostruzione intercensuaria per il 2016–2018, POSAS dal 2019. Non è popolazione pesata né media annuale.</p></div><div><h3 className="font-semibold">Attività ospedaliera</h3><p className="mt-2 text-sm text-muted-foreground">Ministero della Salute, rapporti SDO 2021–2024. Giornate ordinarie e accessi diurni sono presentati separatamente.</p></div></div></Panel>
    <PillarAFlowVisuals annual={data.annual} region={region} regionName={data.regions[region]} group={group} channel={channel}/>
    <footer className="border-t py-3 text-xs text-muted-foreground">VIS Pharma Compass · Fonti pubbliche · Perimetro operativo {data.version}</footer>
  </div>;
}
