"use client";

import { useEffect, useMemo, useState } from "react";
import { ResponsiveContainer, LineChart, Line, BarChart, Bar, CartesianGrid, XAxis, YAxis, Tooltip, Cell } from "recharts";

type Annual = {year:number;region:string;group:string;channel:string;spend:number|null;packs:number|null;spendYoy:number|null;population:number|null;perResident:number|null;missingSpendCells:number;missingPackCells:number;months:number};
type Data = {version:string;regions:Record<string,string>;annual:Annual[];monthly:{year:number;month:number;group:string;channel:string;spend:number|null;packs:number|null}[];activity:{year:number;region:string;ordinary_days:number;day_accesses:number;source_file:string;source_sha256:string;source_cells:string}[];candidates:{atc5:string;group:string;ingredient_or_reference_names:string;aware:string;aware_status:string;public_parent_years:string}[];sources:{file:string;year:number;publisher:string;sha256:string}[]};
const groups:Record<string,string>={antibiotics:"Antibiotici · J01",antifungals:"Antifungini sistemici · J02A",tuberculosis:"Antitubercolari · J04A"};
const channels:Record<string,string>={direct:"Acquisti diretti",convenzionata:"Convenzionata"};
// The SDO editions abbreviate the same region differently; preserve source rows.
const activityName=(name:string)=>name==='Friuli V.G.'?'Friuli Venezia Giulia':name;
const fmt=(v:number|null|undefined,d=0)=>v==null?"N/D":new Intl.NumberFormat("it-IT",{maximumFractionDigits:d}).format(v);
const compact=(v:number)=>new Intl.NumberFormat("it-IT",{notation:"compact",maximumFractionDigits:1}).format(v);
const pct=(v:number|null|undefined)=>v==null?"N/D":`${v>=0?"+":""}${fmt(v*100,1)}%`;
const tipStyle={borderRadius:12,border:"1px solid #d5e3e5",background:"#fff",color:"#173343",boxShadow:"0 12px 30px #17334312"};

function Panel({title,note,children}:{title:string;note:string;children:React.ReactNode}){return <section className="min-w-0 rounded-2xl border bg-card p-5 shadow-sm sm:p-6"><h2 className="font-display text-xl font-semibold">{title}</h2><p className="mb-6 mt-2 text-sm leading-relaxed text-muted-foreground">{note}</p>{children}</section>;}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:Record<string,string>}){return <label className="flex min-w-0 flex-col gap-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">{label}<select className="h-11 rounded-lg border bg-background px-3 text-sm font-medium normal-case tracking-normal text-foreground" value={value} onChange={e=>onChange(e.target.value)}>{Object.entries(options).sort(([a],[b])=>/^\d+$/.test(a)&&/^\d+$/.test(b)?Number(a)-Number(b):0).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>;}

export function PillarAPublic(){
  const [data,setData]=useState<Data|null>(null),[error,setError]=useState(false);
  const [region,setRegion]=useState("000"),[group,setGroup]=useState("antibiotics"),[channel,setChannel]=useState("direct"),[metric,setMetric]=useState("spend"),[activityRegion,setActivityRegion]=useState("ITALIA"),[query,setQuery]=useState("");
  useEffect(()=>{const controller=new AbortController();fetch('/data/pillar-a.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(setData).catch(e=>{if(e.name!=="AbortError")setError(true);});return()=>controller.abort();},[]);
  const annual=useMemo(()=>data?.annual.filter(r=>r.region===region&&r.group===group&&r.channel===channel)??[],[data,region,group,channel]);
  if(error)return <div className="mx-auto max-w-7xl p-10" role="alert">Dati temporaneamente non disponibili. Ricarica la pagina.</div>;
  if(!data)return <div className="mx-auto max-w-7xl p-10" role="status">Caricamento delle serie verificate…</div>;
  const latest=annual.at(-1), metricKey=metric as "spend"|"packs"|"perResident";
  const metricLabel=metric==="spend"?"Spesa riportata (€)":metric==="packs"?"Confezioni riportate":"Spesa per residente (€)";
  const ranked=data.annual.filter(r=>r.year===2025&&r.region!=="000"&&r.group===group&&r.channel===channel&&r[metricKey]!==null).sort((a,b)=>(b[metricKey]??0)-(a[metricKey]??0));
  const seasons=Array.from({length:12},(_,i)=>({month:["Gen","Feb","Mar","Apr","Mag","Giu","Lug","Ago","Set","Ott","Nov","Dic"][i],...Object.fromEntries([2023,2024,2025].map(y=>[String(y),data.monthly.find(r=>r.year===y&&r.month===i+1&&r.group===group&&r.channel===channel)?.spend??null]))}));
  const activity=data.activity.filter(r=>activityName(r.region)===activityRegion);
  const candidates=data.candidates.filter(r=>r.group===group&&`${r.atc5} ${r.ingredient_or_reference_names}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="mx-auto max-w-7xl space-y-8 px-5 py-10 sm:py-14">
    <div className="grid gap-6 md:grid-cols-[1fr_auto]"><div><p className="mb-3 text-xs font-semibold uppercase tracking-[.2em] text-primary">Pillar A / Osservatorio pubblico</p><h1 className="font-display max-w-3xl text-3xl font-semibold leading-tight sm:text-5xl">Dieci anni di dati.<br/><span className="text-primary">Una lettura più precisa.</span></h1><p className="mt-5 max-w-2xl text-base leading-relaxed text-muted-foreground">Spesa e confezioni per territorio, contesto demografico e attività ospedaliera. Fonti pubbliche, perimetri distinti, risultati riproducibili.</p></div><div className="self-end rounded-xl border bg-card p-4 text-sm"><p className="font-semibold">AIFA · ISTAT · Ministero della Salute</p><p className="mt-2 text-muted-foreground">Aggiornamento VIS · 20 settembre 2026</p><a href="/data/pillar-a-annual.csv" download className="mt-4 inline-block font-semibold text-primary underline underline-offset-4">Scarica le serie annuali CSV ↓</a></div></div>
    <div className="grid gap-4 rounded-2xl border bg-card p-5 sm:grid-cols-2 lg:grid-cols-4"><Select label="Territorio" value={region} onChange={setRegion} options={data.regions}/><Select label="Famiglia" value={group} onChange={setGroup} options={groups}/><Select label="Flusso AIFA" value={channel} onChange={setChannel} options={channels}/><Select label="Misura nei grafici" value={metric} onChange={setMetric} options={{spend:"Spesa (€)",packs:"Confezioni",perResident:"Euro per residente"}}/></div>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[
      ["Spesa riportata · 2025",latest?.spend==null?"N/D":`€ ${compact(latest.spend)}`,channels[channel]],
      ["Variazione spesa · 2025 / 2024",pct(latest?.spendYoy),"Stesso territorio, famiglia e flusso"],
      ["Confezioni · 2025",latest?.packs==null?"N/D":compact(latest.packs),"Unità di confezionamento"],
      ["Euro per residente · 2025",latest?.perResident==null?"N/D":`€ ${fmt(latest.perResident,2)}`,"Popolazione al 1° gennaio"],
    ].map(([label,value,note],i)=><div key={label} className={`rounded-2xl border p-5 ${i===0?'bg-[#173b49] text-white':'bg-card'}`}><p className={`text-xs ${i===0?'text-teal-100':'text-muted-foreground'}`}>{label}</p><p className="my-4 font-display text-3xl font-semibold tabular-nums">{value}</p><p className={`text-xs ${i===0?'text-teal-100':'text-muted-foreground'}`}>{note}</p></div>)}</div>
    <p className="rounded-lg border-l-4 border-primary bg-secondary/50 px-4 py-3 text-sm leading-relaxed">{group==="antifungals"?"Gli antifungini hanno una serie dedicata. La classificazione AWaRe non si applica.":group==="tuberculosis"?"Gli antitubercolari sono analizzati separatamente. AWaRe è indicata solo dove presente nel riferimento WHO.":"AWaRe è una classificazione degli antibiotici. Le confezioni di questa serie non sono convertite in DDD."} Il perimetro ATC è costante; le classificazioni correnti costituiscono una lettura retrospettiva.</p>
    <div className="grid gap-6 lg:grid-cols-[1.4fr_1fr]">
      <Panel title="La traiettoria nel tempo" note={`${data.regions[region]} · ${groups[group]} · ${channels[channel]} · ${metricLabel}. Nessuna interpolazione dei valori mancanti.`}><div className="h-80" role="img" aria-label={`Serie annuale ${metricLabel}`}><ResponsiveContainer width="100%" height="100%"><LineChart data={annual} margin={{left:0,right:15,top:10,bottom:5}}><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="#dbe5e8"/><XAxis dataKey="year" tick={{fontSize:11}} axisLine={false} tickLine={false}/><YAxis tickFormatter={compact} tick={{fontSize:11}} width={65} axisLine={false} tickLine={false}/><Tooltip contentStyle={tipStyle} formatter={v=>[fmt(Number(v),2),metricLabel]}/><Line type="linear" dataKey={metricKey} stroke="#13998f" strokeWidth={3} dot={{r:3}} connectNulls={false}/></LineChart></ResponsiveContainer></div></Panel>
      <Panel title="Quanto cambia ogni anno" note="Variazione della spesa rispetto all’anno precedente. Il colore indica la direzione, non un giudizio di performance."><div className="h-80" role="img" aria-label="Variazioni annuali della spesa"><ResponsiveContainer width="100%" height="100%"><BarChart data={annual.map(r=>({...r,change:r.spendYoy==null?null:r.spendYoy*100}))}><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="#dbe5e8"/><XAxis dataKey="year" tick={{fontSize:10}} axisLine={false}/><YAxis tickFormatter={v=>`${v}%`} tick={{fontSize:10}}/><Tooltip contentStyle={tipStyle} formatter={v=>[`${fmt(Number(v),1)}%`,"Variazione"]}/><Bar dataKey="change" radius={[4,4,0,0]}>{annual.map(r=><Cell key={r.year} fill={(r.spendYoy??0)>=0?'#169b91':'#65788b'}/>)}</Bar></BarChart></ResponsiveContainer></div></Panel>
    </div>
    <div className="grid gap-6 lg:grid-cols-2"><Panel title="Profilo mensile nazionale" note={`Italia · ${groups[group]} · ${channels[channel]} · spesa in euro. Il profilo descrive le registrazioni del flusso, non l’incidenza delle infezioni.`}><div className="mb-3 flex gap-5 text-xs">{[2023,2024,2025].map((y,i)=><span key={y} style={{color:['#98aaa9','#52697d','#159b91'][i]}}>● {y}</span>)}</div><div className="h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={seasons}><CartesianGrid strokeDasharray="3 5" vertical={false}/><XAxis dataKey="month" tick={{fontSize:11}}/><YAxis width={65} tickFormatter={compact} tick={{fontSize:11}}/><Tooltip contentStyle={tipStyle} formatter={v=>`€ ${fmt(Number(v))}`}/>{[2023,2024,2025].map((y,i)=><Line key={y} dataKey={String(y)} stroke={['#98aaa9','#52697d','#159b91'][i]} strokeWidth={y===2025?3:1.5} dot={false}/>)}</LineChart></ResponsiveContainer></div></Panel>
    <Panel title="Confronto territoriale · 2025" note={`${metricLabel}. Differenze descrittive: popolazione, composizione e flussi possono variare. Il confronto non identifica risparmi conseguibili.`}><div className="max-h-80 overflow-auto"><table className="w-full text-sm"><thead className="sticky top-0 bg-card text-left text-xs text-muted-foreground"><tr><th className="py-3">Territorio</th><th className="py-3 text-right">{metricLabel}</th></tr></thead><tbody>{ranked.map(r=><tr key={r.region} className="border-t"><td className="py-2.5">{data.regions[r.region]}</td><td className="text-right font-mono">{fmt(r[metricKey],metric==='perResident'?2:0)}</td></tr>)}</tbody></table></div>{metric==='perResident'&&<p className="mt-3 text-xs text-muted-foreground">Bolzano e Trento: N/D, perché le tavole ISTAT regionali qui utilizzate riportano il totale congiunto.</p>}</Panel></div>
    <Panel title="Attività ospedaliera · 2021–2024" note="Fonte SDO, ricoveri per acuti. Giornate ordinarie e accessi diurni sono misure distinte; non sostituiscono il denominatore locale A2."><div className="mb-6 max-w-sm"><Select label="Territorio SDO" value={activityRegion} onChange={setActivityRegion} options={Object.fromEntries([...new Set(data.activity.map(r=>activityName(r.region)))].map(r=>[r,r]))}/></div><div className="grid gap-8 md:grid-cols-2">{(['ordinary_days','day_accesses'] as const).map((k,i)=><div key={k}><h3 className="mb-3 text-sm font-semibold">{i===0?'Giornate di degenza ordinaria':'Accessi in regime diurno'}</h3><div className="h-60"><ResponsiveContainer width="100%" height="100%"><BarChart data={activity}><CartesianGrid vertical={false} strokeDasharray="3 5"/><XAxis dataKey="year"/><YAxis width={70} tickFormatter={compact} tick={{fontSize:11}}/><Tooltip contentStyle={tipStyle} formatter={v=>fmt(Number(v))}/><Bar dataKey={k} fill={i===0?'#173b49':'#159b91'} radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></div>)}</div></Panel>
    <Panel title="Classificazione e copertura dei riferimenti" note="Inventario dei codici presenti nei riferimenti AIFA/WHO disponibili. Presenza in anagrafica e presenza nel flusso non sono equivalenti. Il flusso pubblico arriva al gruppo ATC4, non alla singola molecola."><input aria-label="Cerca codice o principio attivo" placeholder="Cerca codice ATC o principio attivo…" className="mb-4 w-full rounded-lg border bg-background px-4 py-3 text-sm" value={query} onChange={e=>setQuery(e.target.value)}/><p className="mb-3 text-xs text-muted-foreground">{candidates.length} codici · WHO AWaRe 2025</p><div className="max-h-80 overflow-auto"><table className="w-full text-left text-sm"><thead className="sticky top-0 bg-card text-xs text-muted-foreground"><tr><th className="p-2">ATC</th><th className="p-2">Principio attivo / voce di riferimento</th><th className="p-2">AWaRe</th></tr></thead><tbody>{candidates.map(r=><tr key={r.atc5} className="border-t"><td className="p-2 font-mono">{r.atc5}</td><td className="p-2">{r.ingredient_or_reference_names}</td><td className="p-2">{r.aware||(r.aware_status==='not_applicable'?'Non applicabile':'Non classificato')}</td></tr>)}</tbody></table></div></Panel>
    <Panel title="Dalla visualizzazione alla fonte" note="Ogni serie conserva periodo, flusso e fonte. Le celle vuote non diventano zero; le somme rappresentano i valori numerici riportati."><div className="grid gap-6 md:grid-cols-3"><div><h3 className="font-semibold">Spesa e confezioni</h3><p className="mt-2 text-sm text-muted-foreground">AIFA 2016–2025. Acquisti diretti e convenzionata sono separati; non equivalgono automaticamente ai canali locali DD e CO.</p><a className="mt-3 block text-sm text-primary underline" href="https://www.aifa.gov.it/spesa-e-consumo-relativi-al-flusso-della-farmaceutica-convenzionata-e-degli-acquisti-diretti">Fonte AIFA ↗</a></div><div><h3 className="font-semibold">Popolazione residente</h3><p className="mt-2 text-sm text-muted-foreground">ISTAT, 1° gennaio 2019–2025. Non è popolazione pesata né media annuale. Prima del 2019 il tasso è N/D.</p><a className="mt-3 block text-sm text-primary underline" href="https://demo.istat.it/app/?i=POS">Fonte ISTAT ↗</a></div><div><h3 className="font-semibold">Attività ospedaliera</h3><p className="mt-2 text-sm text-muted-foreground">Tavola SDO 2.1.6, 2021–2024. I totali territoriali riconciliano con Italia. Per A2 servono le definizioni dell’Azienda.</p><a className="mt-3 block text-sm text-primary underline" href="https://www.salute.gov.it/new/it/tema/assistenza-ospedaliera/rapporti-annuali-sui-ricoveri-ospedalieri/">Rapporti SDO ↗</a></div></div><details className="mt-6 border-t pt-4"><summary className="cursor-pointer text-sm font-semibold">Tabella annuale e qualità dei valori selezionati</summary><div className="mt-4 overflow-auto"><table className="w-full text-left text-xs"><thead><tr>{['Anno','Spesa €','Confezioni','€/residente','Celle spesa vuote','Mesi'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{annual.map(r=><tr key={r.year} className="border-t"><td className="p-2">{r.year}</td><td>{fmt(r.spend,2)}</td><td>{fmt(r.packs,2)}</td><td>{fmt(r.perResident,2)}</td><td>{r.missingSpendCells}</td><td>{r.months}</td></tr>)}</tbody></table></div><a href="/data/pillar-a.json" className="mt-4 block text-primary underline">Dati pubblici e impronte SHA-256</a></details></Panel>
    <footer className="border-t py-3 text-xs text-muted-foreground">VIS Pharma Compass · Fonti pubbliche · Perimetro operativo {data.version} · Analisi locali disponibili nell’area autorizzata.</footer>
  </div>;
}
